version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'SAE410'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./app/sae410.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      SAE41_network:
        ipv4_address: 172.20.0.10

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: unless-stopped
    networks:
      SAE41_network:
        ipv4_address: 172.20.0.20

  adminer:
    build:
      context: .
      dockerfile: Dockerfile.adminer
    restart: unless-stopped
    container_name: adminer
    networks:
      SAE41_network:
        ipv4_address: 172.20.0.30

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    container_name: nginx
    networks:
      SAE41_network:
        ipv4_address: 172.20.0.1

# Names our volume
volumes:
  my-db:

networks:
  SAE41_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
