version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

  fastapi:
    build: .
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: unless-stopped
    volumes:
      - fastapi:/var/lib/fastapi

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiZTk4ZWNlMDhhN2QwNDRmMjk1Yjc3NTY0YmExM2NhMjQiLCJ0IjoiZDEzMTAwZWMtOWU3Ny00YjVlLTg5YTYtZTFhMzQxODQ5YjBkIiwicyI6Ik5tUTBNREpoTWpZdE16SXlPUzAwTldRMkxUa3hPVE10WXpkbVpXTTBNVGMyTkdNeCJ9
# Names our volume
volumes:
  my-db:
  fastapi:
