FROM debian:11

WORKDIR /app

RUN apt update && apt upgrade -y

RUN apt install python3-pip -y

RUN pip install uvicorn fastapi jinja2 mysql-connector-python fastapi-responses python-multipart httpx fastapi-login

RUN pip install --upgrade fastapi uvicorn httpx

COPY ./app/ ./

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
